# Change these first
owner: jessgusclark # Your GitHub organization or username, where this repository lives
repo: psr-upptime # The name of this repository

sites:
  - name: Live Public Site
    url: https://practicesightreading.com
  - name: Music Builder Health Endpoint
    url: $BUILD_SERVER/__health
  - name: Request music from Music Builder
    url: $BUILD_SERVER/request
    method: POST
  - name: Staging Server
    url: $STAGING_SERVER
  - name: Image Server
    url: https://i.practicesightreading.com/

assignees: # Users to assign downtime issues (optional)
  - jessgusclark

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /psr-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Practice Sight Reading Upptime
  introTitle: Realtime status of Practice Sight Reading. 
  introMessage: This site checks the status of the website, however, if you find issues please let Jesse know at <a href="mailto:jesse@practicesightreading.com">jesse@practicesightreading.com</a>
  navbar:
    - title: Status
      href: /
    - title: Live Site
      href: https://practicesightreading.com

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
